require 'slack-ruby-bot'
require './slack-qbot/lib/queue'
require './slack-qbot/lib/redis/queue_support.rb'
require './slack-qbot/lib/redis/application_support.rb'
require 'pry-remote'
require './slack-qbot/version'
require './slack-qbot/about'
require './slack-qbot/commands'
require './slack-qbot/lib/environment'
require './slack-qbot/lib/application'
require './slack-qbot/lib/repository'
require './slack-qbot/lib/work'
require './slack-qbot/lib/workers/queue_worker.rb'
require './slack-qbot/lib/bot'
require './slack-qbot/lib/redis/queue_support.rb'

SlackRubyBot::Client.logger.level = Logger::WARN
